title: AI Discovery Blog
description: Discover the latest tools, breakthroughs, and trends in Artificial Intelligence.
baseurl: ""
url: "https://ruirodsantos.github.io/ai-discovery-blog"

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
future: true
