
title: AI Discovery Blog
description: Stay updated with the latest news and trends in Artificial Intelligence.
author: Rui Rodrigues dos Santos
email: hello@adventis.ai
baseurl: ""
url: "https://ruirodsantos.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
