title: AI Discovery Blog
email: hello@adventis.ai
description: >-
  Discover the latest tools, breakthroughs, and trends in Artificial Intelligence.
baseurl: "/ai-discovery-blog" # important for subfolder hosting
url: "https://ruirodsantos.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
